### ISSUE TITLE
Progress tracker: Быков Илья

### ISSUE THREAD

**Issue by dkurt** [dkurt/llama2.c.riscv#7]
- [x] Проект запущен на x86
- [x] Проект запущен на RISC-V без регрессии
- [x] Предложены тесты (PR)
- [x] Анализ производительности - метод (с примером команд или кодом) и результат. Доказать стабильность (написать результаты в комментариях к этой задаче)
- [x] Hotspot анализ + выбрана функция для оптимизации (написать результаты в комментариях к этой задаче)
- [x] Раунд оптимизации (PR)
- [x] 1-2 слайда о своих результатах

**Comment by b-ilya-code** [comment]
Результаты бенчмарка
![Снимок](https://github.com/dkurt/llama2.c.riscv/assets/132210206/e96d4dd6-6256-4e48-94e2-114eb615704b)

**Comment by b-ilya-code** [comment]
Бенчмарк проводился для запроса: run stories110M.bin -s 124 -i "Hello, dear friend," -t 0.42 -p 0.42 -n 200
Токенов в секунду: 4.903289
Функция forward выполняется 215 ms

Далее приведены замеры времени выполнения функций, вызываемых в forward, и процент их времени выполнения относительно времени выполнения forward:
1. matmul - 190 ms, 88%
2. multihead attention (блок кода) - 25 ms, 11%
3. softmax - 2 ms, 1%
4. rmsnorm - 0 ms, 0%
5. RoPE (блок кода) - 0 ms, 0%
6. SwiGLU (блок кода) - 0 ms, 0%

**Comment by b-ilya-code** [comment]
[Быков Илья, результаты.pdf](https://github.com/dkurt/llama2.c.riscv/files/14191177/default.pdf)

**Comment by b-ilya-code** [comment]
[Защита проекта NLP на RISC-V.pptx](https://github.com/dkurt/llama2.c.riscv/files/14191911/NLP.RISC-V.pptx)
